### ISSUE TITLE
Cache form content

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/nasa-apt-frontend#340]
While it is not saved the atbd form content should be saved to localstorage to allow recovering it if case of error.

**Comment by oliverroick** [comment]
Couple of questions on the scope of this:

- How many forms do we want to cache? Only the latest one, all that have ever been edited and not saved?
- How long do we want to keep the cache? Do we want to expire the cache after some time?
- Assuming that we remove a form from cache once it has been saved.
- And then we have the old edit conflicts: How do we want to deal with those? Say, I start editing the document and then go for lunch without saving. Then Anthony fixes a couple of typos and saves. After lunch, I come back and make some more edits and save. What happens? I know, we have this problem anyway but this is becoming more likely once we keep edits in local storage that persist after closing a browser window, potentially even beyond the current user session. 

To me this feels like one of these features where the scope increases the longer you think about this and we need to be careful what we commit to.

**Comment by aboydnw** [comment]
1. Only the latest one. We have other features that warn users about leaving a page without saving so I think we are most worried about whatever form they are currently editing.
2. The main use cases we want to solve with this ticket are when somebody has to refresh (because of an error or other reason) or accidentally navigates away from the page. In those cases, I think we can assume that they will return fairly quickly. With that in mind, I don't think we have to keep the cache for very long. Maybe something as short as 60 seconds? To be honest I am not knowledgable on how caches get wipes or updated so that might be an ignorant response.
3. I agree with your assumption
4. Hopefully our approach to #2 of only keeping the cache for a very short amount of time would minimize this conflict. We have also discussed a feature that would disallow editing of the same section while somebody else has it open, which would fully eliminate this issue, but we wouldn't need to develop that until later.
