### ISSUE TITLE
Bug:  New user sign up in APT fails

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt-frontend#341]
**High Priority Fix**

Both Aaron and I are having issues signing up in APT and when trying to create a user, its not showing up in the GCC Cognito service. Something doesn't appear to be talking correctly.

To see the error comment, go to sign in page and select "sign up" it states "An error was encountered with the requested page"

**Comment by aboydnw** [comment]
@deborahUAH @kaulfusa Which URL were you testing from? I was under the impression you were testing in staging for the time being, but can try signing up on my machine if you are on a different URL.

cc @leothomas

**Comment by deborahUAH** [comment]
Since GCC was working, I was using GCC APT at http://algorithm-publication-tool.s3-website.us-west-2.amazonaws.com/apt/,  the URL Daniel provided in his email of last week.

**Comment by aboydnw** [comment]
@deborahUAH To circle back on this. There is an issue that exists within the GCC instance of APT as it relates to the redirect to cognito registration. This will not be an issue once the migration occurs. The rest of the functionality in GCC should be the same as what is in staging. Otherwise, the login/signup workflow should work as expected in staging.

I'll close this ticket, pasting here the comment from Leo in slack.

> we haven't yet migrated the production APT url from the UAH stack to the GCC stack (which is accessible at http://algorithm-publication-tool.s3-website-us-west-2.amazonaws.com/apt/ for the time being). Once we have the green light on that, we'll clear out the GCC database, load up the data from the UAH prod and re-direct that url
